language: java

jdk: 
  - oraclejdk12

services:
  - docker


before_install:
  - docker pull openjdk:12


# Test & Build SpringBoot app
script:
  - ./gradlew build


# Create Docker image for our app and push it to Dockerhub repository
after_success:
  - TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH--$COMMIT"; fi`
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker-compose build
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG


# Allow Travis to help deploy the app on Heroku
deploy:
  provider: heroku
  api-key:
    secure: "$HEROKU_API_KEY"
  app: ordersapi
  on:
    tags: true
    repo: "$IMAGE_NAME"
  