INSERT INTO CUSTOMER(NAME, EMAIL, PHONE) VALUES('Aragorn', 'aragorn@email.com', '+559999999');
INSERT INTO CUSTOMER(NAME, EMAIL, PHONE) VALUES('Legolas', 'legolas@email.com', '+559999999');
INSERT INTO CUSTOMER(NAME, EMAIL, PHONE) VALUES('Gimli', 'gimli@email.com', '+559999999');
INSERT INTO CUSTOMER(NAME, EMAIL, PHONE) VALUES('Gandalf', 'boromir@email.com', '+559999999');
INSERT INTO CUSTOMER(NAME, EMAIL, PHONE) VALUES('Frodo', 'frodo@email.com', '+559999999');
INSERT INTO CUSTOMER(NAME, EMAIL, PHONE) VALUES('Bilbo', 'bilbo@email.com', '+559999999');


INSERT INTO ADDRESS(NUMBER, STREET, CITY, POSTCODE, COUNTRY, CUSTOMER_ID)
    VALUES('Bag End', 'Bag End way', 'Hobbiton', '00000-000', 'Middle earth', 6);
