INSERT INTO CUSTOMER(NAME, EMAIL, PHONE) VALUES('Aragorn', 'aragorn@email.com', '+559999999');
INSERT INTO CUSTOMER(NAME, EMAIL, PHONE) VALUES('Legolas', 'legolas@email.com', '+559999999');
INSERT INTO CUSTOMER(NAME, EMAIL, PHONE) VALUES('Gimli', 'gimli@email.com', '+559999999');
INSERT INTO CUSTOMER(NAME, EMAIL, PHONE) VALUES('Gandalf', 'boromir@email.com', '+559999999');
INSERT INTO CUSTOMER(NAME, EMAIL, PHONE) VALUES('Frodo', 'frodo@email.com', '+559999999');
INSERT INTO CUSTOMER(NAME, EMAIL, PHONE) VALUES('Bilbo', 'bilbo@email.com', '+559999999');


INSERT INTO ADDRESS(NUMBER, STREET, CITY, CUSTOMER_ID)
    VALUES('111', 'Wall Street', 'Condado', 1);
